# -*- coding: utf-8 -*-
"""PyBank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XR2t_tr9-riZvmfc5BjWBDHPEy1Cwn7n
"""

import pandas as pd
import numpy as np

df= pd.read_csv("Resources/budget_data.csv")
df.head(1)

df.info()

#* The total number of months included in the dataset
df["Month"]=df["Date"].str.split("-").str.get(0)
df["date"]=df["Date"].str.split("-").str.get(1)
print(" Total Months:",df["Month"].count())
#f["Month"].count()

df

#* The net total amount of "Profit/Losses" over the entire period
print("total amount of \"Profit/Losses\"",df["Profit/Losses"].sum())

changes=[0]
peroids=[]
for i in range(0,85):
    change=df["Profit/Losses"][i+1]-df["Profit/Losses"][i]
    changes.append(change)
    
    #print(df["Date"][i]," to" ,df["Date"][i+1], change)

df["changes"]=pd.Series(changes)
df

# The changes in "Profit/Losses" over the entire period, and then the average of those changes
print("Average Change:",df["changes"].mean())

#* The greatest increase in profits (date and amount) over the entire period


# find the max chnage in profit 
df["changes"].max()
df_max_profit=df[df["changes"]==1862002]

print("Greatest Increase in Profits:",df_max_profit['Date'].values[0],"$",df_max_profit['changes'].values[0])

#* The greatest decrease in profits (date and amount) over the entire period

# find the max chnage in profit 
df["changes"].min()
df_min_profit=df[df["changes"]==-1825558]
df_min_profit
print(" Greatest Decrease in Profits:",df_min_profit['Date'].values[0],"$",df_min_profit['changes'].values[0])

import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(15, 8)) 
plt.plot(df["Date"],df["Profit/Losses"],label="overall trend")
plt.scatter(df_min_profit["Date"],df_min_profit["Profit/Losses"],color="red",label="greatest decrease")
plt.scatter(df_max_profit["Date"],df_max_profit["Profit/Losses"],color="green",label="greatest increase")
plt.legend(loc="upper left")
plt.xticks(rotation=90)
plt.show()